name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  tests:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        php_version: ['7.4', '8.0']
        os: [ubuntu-latest, macOS-latest, windows-latest]


    steps:
    - uses: actions/checkout@v2

    - name: Validate composer.json and composer.lock
      run: composer validate --strict

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v2
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress --no-suggest

    - name: Run PHPStan
      run: composer run-script analyse

    - name: Run PHPUnit
      run: composer run-script test
      
  code_coverage:
    name: Code Coverage
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v2
        - uses: shivammathur/setup-php@v2

        - run: composer install --prefer-dist --no-progress --no-suggest
        - run: composer run-script test-coverage
        - run: wget https://github.com/php-coveralls/php-coveralls/releases/download/v2.4.3/php-coveralls.phar
        - env:
              COVERALLS_REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          run: php php-coveralls.phar --verbose --config .coveralls.yml
